### ISSUE TITLE
Animated GIFs

### ISSUE THREAD

**Issue by DIETRICHvonDOEDEL** [mhwlng/streamdeck-elite#1]
First of all thank you for the great Tool for Stream Deck. 
Stream Deck natively supports animated GIFs for the Icons. Trying with streamdeck-elite gives me static icons. Is there any chance to get animated GIFs work with streamdeck-elite? I would love to have flahing or pulsing icons on some functions.
![cargo_on](https://user-images.githubusercontent.com/56312724/67982026-29b00580-fc22-11e9-936b-13a333503a93.gif)

**Comment by mhwlng** [comment]
SetImage doesn't support animated gifs.

reply from elgato on reddit :
https://www.reddit.com/r/StreamDeckSDK/comments/e0g0y6/when_i_use_setimage_with_an_animated_gif_i_only/fb786o8?utm_source=share&utm_medium=web2x
