### ISSUE TITLE
FSS Button Incorrectly Labelled

### ISSUE THREAD

**Issue by TenroNamikaze** [mhwlng/streamdeck-elite#10]
The New FSS Button is Incorrectly Labelled as FSD
![FSS Button](https://user-images.githubusercontent.com/14202783/84835902-897de400-b02c-11ea-851e-2eab27aba972.png)

**Comment by mhwlng** [comment]
fixed in version 2.0.5

a4c1a6b0200db96a7516398ed624edffe059551a
