### ISSUE TITLE
Mapping to some numpad keys (/*-+) does not work

### ISSUE THREAD

**Issue by pvbrakel** [mhwlng/streamdeck-elite#11]
I found some keys not working that I mapped to numpad multiply, divide , add and substract.
In the logfile there is an exception:
Requested value 'DIKNUMPADDIVIDE' was not found.
Requested value 'DIKNUMPADMULTIPLY' was not found.
Requested value 'DIKNUMPADADD' was not found.
while trying to parse the string to enum DirectInputKeyCode.

Must be caused by these keys are actually called DikMultiply, DikDivide, DikSubtract, DikAdd in the used enum.

P.S. Thanks for developing this plugin and making it freely available for us, greatly appreciated!

**Comment by mhwlng** [comment]
This is now fixed in 2.0.6
