### ISSUE TITLE
Elite not accepting button presses

### ISSUE THREAD

**Issue by sollisb** [mhwlng/streamdeck-elite#16]
HI 👍 

Everything on the Elgato seems to work, log files show the mhwlng power buttons etc being pressed.  But.. Elite does nothing.

I tested iusing notepad++, all button presses show as being active,

Yes I have the latest.  'Custom' is in the presets.

It's really weird and a little annoying.  I even wrote a program to watch the log file and it shows every press I make.  It's just Elite that appears to ignore them.

Any help much appreciated.  Oh!  Yes, when I press the L key for example; Landing gear drops, the elgato icon changes.  If I press The elgato key, nothing happens and nothing changes.

cheers

Ben

**Comment by mhwlng** [comment]
I'm afraid I have no idea what it could be?

Here's somebody else with the same problem :

https://forums.frontier.co.uk/threads/v1-2-0-elgato-stream-deck-button-plugin-for-elite-dangerous.534521/page-4#post-8582392

He tried the streamdeck 'hotkey' button, which has nothing to do with the plugin, and that also didn't work for him ?

I assume that you are not using a tool like autohotkey or voiceattack configured to block keypresses?

**Comment by TenroNamikaze** [comment]
Are you running the stream deck program as administrator?

**Comment by sollisb** [comment]
yep, administrator mode needed.. Thanks guys!  

Also willing to help if anything needs adding..
