### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by Andechs75** [mhwlng/streamdeck-elite#17]
Hello there,
FlightAssist should be bound to the Y-Key. With my Keyboard and the Hotas it works as intended. But with the Deck (XL) and the ToggleButton FlightAssist i get a Z-Keystroke. The feedback of the Status.json and the image seems to work. I think i have an issue with the german keyboard layout. If i use a normal Hotkey for Z and Y it works, too. Somehow it reads the de-DE binds and the Output of the Plugin is an USB[hex] Code for en-EN devices. Any Ideas to fix it, or to work arround this issue?
Rest is working great. Thx for the plugin.

.binds:
KeyboardLayout de-DE /KeyboardLayout
...
ToggleFlightAssist
	Primary Device="{NoDevice}" Key="" /
	Secondary Device="Keyboard" Key="Key_Y" /
	ToggleOn Value="1" /
/ToggleFlightAssist
SelectHighestThreat
	Primary Device="{NoDevice}" Key="" /
	Secondary Device="Keyboard" Key="Key_Z" /
/SelectHighestThreat

.log:
monitoring key binding path #1 C:\Users\##\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings
monitoring key binding file name #1 StartPreset.start
monitoring key binding path #2 C:\Users\##\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings
monitoring key binding file name #2 Warthog-v421.3.0.binds

**Comment by mhwlng** [comment]
fixed in v 2.1.1
