### ISSUE TITLE
some binds don't look like their reading

### ISSUE THREAD

**Issue by ulfartorhild** [mhwlng/streamdeck-elite#18]
just started using it, pretty awesome work i really like it, but some of the binds don't seem to be being read as i try to use super cruise or FSD or even my throttle % markers none of them work. cheers

**Comment by mhwlng** [comment]
you need keyboard bindings.
If you have only a joystick/mouse/controller binding then it won't work...
If that is not the problem, then please post your binds file here.

**Comment by ulfartorhild** [comment]
Yeah I know I have them set its reading all my throttle as right control which is half the bind. Does it not accept multi key binds? (only using those as an example it not just them) here are my binds 
[Mine.3.0.docx](https://github.com/mhwlng/streamdeck-elite/files/5078685/Mine.3.0.docx)

**Comment by mhwlng** [comment]
>>try to use super cruise or FSD 

you don't have any keyboard binding for supercruise or hyperspace :

	<Supercruise>
		<Primary Device="SaitekX56Throttle" Key="Joy_6" />
		<Secondary Device="{NoDevice}" Key="" />
	</Supercruise>
	<Hyperspace>
		<Primary Device="SaitekX56Throttle" Key="Joy_3" />
		<Secondary Device="{NoDevice}" Key="" />
	</Hyperspace>

**Comment by ulfartorhild** [comment]
yeah i realised i didn't have my supercruise or hyperspace jump ones set to keyboard and elite is doing that thing where if i try and change shit it wipes my hole file which has just happened trying to fix now -.- cheers for your fast response i'll let you know how i go

**Comment by mhwlng** [comment]
all the throttle key  bindings are wrong :

```
<Primary Device="Keyboard" Key="Key_RightControl">
<Modifier Device="Keyboard" Key="Key_0" />
</Primary>

```
it should look like this : i.e. the modifier is the crt/shift/alt key

```
<Primary Device="Keyboard" Key="Key_0">
<Modifier Device="Keyboard" Key="Key_RightControl" />
</Primary>

```

**Comment by ulfartorhild** [comment]
ah fair enough i didn't know there was a specific way i was supposed to have them i just hit them and thats how they came out, i had it set with macros before... OMG its not saving my binds now gah this damned game i love to hate it haha

**Comment by mhwlng** [comment]
I've noticed that there is a problem with key modifiers (alt/shift/ctrl) on the primary binding.
I'll fix that in the next version.
in the mean time, you can add the key to the secondary binding. (the right column in elite)

**Comment by ulfartorhild** [comment]
cool as. i tried rebinding but now elite has gone off and deleted my bindings and won't star with the bindings i tell it to in the startpreset.start file. i got it working before then i tried using you app and tried changing a key binding to get the app to work fully and elite did it again (not your fault elite is just broken) so no it only seems to want to load in with keyboard and mouse setting and doesn't even read that i have a custom binds file let alone my other one.

**Comment by mhwlng** [comment]
f.y.i. new version is released :

handle alt/shift/ctrl modifiers for primary key bindings
handle hash key on British keyboard
