### ISSUE TITLE
Autoswitch "back to main" ?

### ISSUE THREAD

**Issue by Andechs75** [mhwlng/streamdeck-elite#19]
Hi there,
I tried the profile switching. It switched perfectly to the Map-Profiles. But when i leave the map, it won't switch back to main.
Did i missed something?
Thx for your efford,
CMDR Andechs
[pluginlog.log](https://github.com/mhwlng/streamdeck-elite/files/5159289/pluginlog.log)

**Comment by Andechs75** [comment]
Some hints on this issue:
In AnalysisMode Maps won't switch to Main or Analysis. But if the Ship is in CombatMode it works!

**Comment by mhwlng** [comment]
that narrows it down, thanks...

**Comment by mhwlng** [comment]
fixed in 2.1.4

**Comment by Andechs75** [comment]
It's still an issue, here.

- If the ship is in analysis i can switch to and between the map profiles, but it won't switch back to analysis. If the ship is in combat mode (wich is main) it works.
- If the hardpoints are retracted the same issue occurs. It won't switch back from maps to hardpoints.
- Switching form hardpoints to analysis works, analysis to hardpoints isn't.
- Switching analysis or hardpoints directly to main is ok.

I will implement further profiles, and will see what happens..
CMDR Andechs

[manifest.txt](https://github.com/mhwlng/streamdeck-elite/files/5182319/manifest.txt)
[pluginlog.log](https://github.com/mhwlng/streamdeck-elite/files/5182382/pluginlog.log)

**Comment by mhwlng** [comment]
I don't understand

>>If the hardpoints are retracted the same issue occurs. It won't switch back from maps to hardpoints.

if the hardpoints are retracted it's not supposed to switch to hardpoints, only when hardpoints are deployed ?

**Comment by Andechs75** [comment]
- hardpoints deploy (it switches to hardpoints)
- switch to map (it switches to map)
- close map
- stuck (won't switch back to hardpoints)

**Comment by mhwlng** [comment]
ok, I'll investigate further when I have time...

**Comment by Andechs75** [comment]
> ok, I'll investigate further when I have time...

i whished i could help you with coding, but's not my language...

**Comment by mhwlng** [comment]
why did you close this? it's not fixed

**Comment by Andechs75** [comment]
How you trigger the switching with the status.json?
I guess GuiFocus used for maps, fss, saa and Flags for e.g. HudInAnalysisMode, right?

**Comment by mhwlng** [comment]
see elitebase.cs ontick()

**Comment by mhwlng** [comment]
version 2.1.5 should fix the problem
