### ISSUE TITLE
Does the toggle button actually toggle the item in Elite?

### ISSUE THREAD

**Issue by IainMNorman** [mhwlng/streamdeck-elite#2]
I'm not sure if I'm being dense or not but is this just for a visual display of the toggle state, or is the stream deck button supposed to toggle the function chosen? Because it doesn't do so for me.

**Comment by IainMNorman** [comment]
Ahah! Fixed it. Yes it does.

For some reason my StartPreset.start did not contain the correct name of my custom bindings due to the them having 3.0. included in their filename.

**Comment by IainMNorman** [comment]
I do notice though that the plugin does is not simulating some of my bindings. Such as the chorded combinations I use on my gamepad.

eg. Cargo Scoop is set to A + Dpad-up.

The toggle button for this does nothing. To fix it I have to assigned a keyboard key to it in Elite. Then the toggle button works. After restarting the streamdeck app.

**Comment by IainMNorman** [comment]
Looking at the code it appears this is by design, keyboard only :-)
Easy enough to setup. All working nice now.

**Comment by mhwlng** [comment]
new version is published that checks .3.0.binds file before .binds file

**Comment by IainMNorman** [comment]
Ahah. Thanks. I was just about to go do that myself :) Save me a PR. Good chap!
