### ISSUE TITLE
Profiles wont load.

### ISSUE THREAD

**Issue by NovemberFalls** [mhwlng/streamdeck-elite#20]
Howdy, I have followed this guide as best as I could though profiles will not load...

1. Download and ran the [plugin](https://github.com/mhwlng/streamdeck-elite/wiki/Automatic-Profile-Switching)
2. Downloaded the [main version](https://github.com/mhwlng/streamdeck-elite)
3. Created and configured the profiles in Stream Deck
4. Exported them into the plugin folder
5. Changed manifest with needed information
6. Deleted profiles
7. rebooted stream deck
8. Never get a prompt / attempt manual, never loads
9. I have also tried as admin

Thoughts?

This is what I added into profiles 
  "Profiles": [
  {
    "Name": "Elite Dangerous Main",
    "ReadOnly": true,
    "Device Type": 0,
    "DontAutoSwitchWhenInstalled": false
  },
  { "Name": "Elite Dangerous Hardpoints",
    "ReadOnly": true,
    "Device Type": 0,
    "DontAutoSwitchWhenInstalled": false
    },
    {    "Name": "Elite Dangerous Navigation",
    "ReadOnly": true,
    "Device Type": 0,
    "DontAutoSwitchWhenInstalled": false
    }

Profile names match

Thanks in advance, You Rock!

07 CMDR Falls

**Comment by mhwlng** [comment]
You need to post the full profile file and also the log file

**Comment by NovemberFalls** [comment]
[pluginlog.log](https://github.com/mhwlng/streamdeck-elite/files/5177765/pluginlog.log)

[Profiles.zip](https://github.com/mhwlng/streamdeck-elite/files/5177767/Profiles.zip)

Also, I posted the profiles within the com.mhw plugin.

Thanks for the quick reply.

**Comment by mhwlng** [comment]
can you please post the manifest.json

**Comment by NovemberFalls** [comment]
[com.mhwlng.elite.sdPlugin - Copy.zip](https://github.com/mhwlng/streamdeck-elite/files/5177782/com.mhwlng.elite.sdPlugin.-.Copy.zip)
this is a full copy of the plugin.

**Comment by mhwlng** [comment]
it's not

"Device Type": 0

but

"DeviceType":0,

**Comment by NovemberFalls** [comment]
So Ill change it from

"Name": "Elite Dangerous Navigation",
    "ReadOnly": true,
    "Device Type": 0,
    "DontAutoSwitchWhenInstalled": false

to

"Name": "Elite Dangerous Navigation",
    "ReadOnly": true,
    "Device Type":0,
    "DontAutoSwitchWhenInstalled": false

Just a sec.

Edit: Whoops, I see it now. 1 more sec.

**Comment by mhwlng** [comment]
no, "Device Type":0 is wrong

**Comment by NovemberFalls** [comment]
I just realized what you meant. 

That worked! Sometimes I hate coding... 👍 

Thanks for the quick replies!
