### ISSUE TITLE
Profile switching

### ISSUE THREAD

**Issue by Andechs75** [mhwlng/streamdeck-elite#21]
It's still an issue, here.

- If the ship is in analysis i can switch to and between the map profiles, but it won't switch back to analysis. If the ship is in combat mode (wich is main) it works.
- If the hardpoints are retracted the same issue occurs. It won't switch back from maps to hardpoints.
- Switching form hardpoints to analysis works, analysis to hardpoints isn't.
- Switching analysis or hardpoints directly to main is ok.

I will implement further profiles, and will see what happens..
CMDR Andechs

[manifest.txt](https://github.com/mhwlng/streamdeck-elite/files/5182319/manifest.txt)
[pluginlog.log](https://github.com/mhwlng/streamdeck-elite/files/5182382/pluginlog.log)

_Originally posted by @Andechs75 in https://github.com/mhwlng/streamdeck-elite/issues/19#issuecomment-688211607_

**Comment by mhwlng** [comment]
closing this, please continue in other issue
