### ISSUE TITLE
SRV: Toggles buggy

### ISSUE THREAD

**Issue by CSchmidtDD** [mhwlng/streamdeck-elite#22]
Hey @mhwlng and first of all great job on this fantastic Plugin for the Stream Deck!

I'd like to address two issues with the current Release that focus on toggle functions while being in the SRV.

### SRV Cargo Scoop
**Expected Behaviour:**
-> Toggle Button for Cargo Scoop (used on the ship) should deploy Cargo scoop for SRV, as there is no dedicated SRV Cargo Scoop Option available (referring to the _Cargo Scoop_ Keybind under _Driving Miscellaeneous_)
**Actual Behaviour:**
-> Does not Deploy or Retract SRV Cargo Scoop, but it correctly indicated the actual state of the scoop.

### SRV Lights
**Expected Behaviour:**
-> Toggle Button for Lights should toggle the (head-)lights on the SRV. (Referring to the keybind _Headlights_ under Driving)
**Actual Behaviour:**
-> It correctly indicates the on/off state of the lights, regardless of the third state. (Full Beam/DippedBeam)-On/(Off)-Off

If you feel comfortable with some additions, I can check out how I can contribute best to solve this issue and maybe add some useful funcationality. :)

Best Regards

**Comment by mhwlng** [comment]
The idea is that you set up the same key bindings for SRV and ship lights/cargo scoop.
then it works ok, right ?

**Comment by CSchmidtDD** [comment]
I'm afraid this is exactly how it is supposed to work and it does.
How did I not manage to check for different keybinds, I don't know.

Thanks for clearing this behaviour up. 
I'd be glad to fill an FAQ Page regarding double-keybinding certain features to work on ship and srv, because I didn't find that very intuitive at first from FDev.

Thanks for your quick response and easy solution 👍

**Comment by mhwlng** [comment]
I'll change it anyway

there is a status flag 'InSrv' in status.json

so when the button is pressed, I can use either the ship binding or the srv binding depending on that flag

**Comment by mhwlng** [comment]
changed in 2.1.6
