### ISSUE TITLE
Nightvision button isn't working anymore.

### ISSUE THREAD

**Issue by RoyLachman** [mhwlng/streamdeck-elite#24]
Hi mhwlng,

It seems with the latest update the night-vision toggle button doesn't seems to work anymore. Every other Toggle button does work. Whenever i manually turn on night vision in key with my keyboard bind it does show to toggle in icon's if you've set one for on and off.  But when pressing the button on my stream-deck it doesn't switch between on or off.  

What i've tried so far: Removing the button and placing a new fresh Toggle Button with the fuction Night Vision but to bad that didn't work :(

**Comment by mhwlng** [comment]
please post your binding file and the log file

I just tested it on my system and the night vision button works for me ? (it works the same as all the other toggle buttons)

I'm using this binding to test :
```
<NightVisionToggle>
   <Primary Device="Keyboard" Key="Key_N" />
   <Secondary Device="{NoDevice}" Key="" />
</NightVisionToggle>
```

What version did work for you ?
if you re-install that exact version, does it work for you again ?

I can't think of any reason why the latest version would break a single toggle button (and not any of the others) ?
nothing has changed recently (other than playing a sound, only if it there is one defined)

**Comment by mhwlng** [comment]
What version did it work for you ?
if you install that version now, does it work again ?

I can't see any reason why the latest version would break a single toggle button ?
nothing has changed (other than playing a sound if it there is one)

**Comment by mhwlng** [comment]
I just tested it on my system and the night vision button works for me ? (it works the same as all the other toggle buttons)

I'm using this button to test :
```<NightVisionToggle>
	<Primary Device="Keyboard" Key="Key_N" />
	<Secondary Device="{NoDevice}" Key="" />
</NightVisionToggle>```

**Comment by RoyLachman** [comment]
`	<NightVisionToggle>
		<Primary Device="Keyboard" Key="Key_N" />
		<Secondary Device="Keyboard" Key="Key_5" />
	</NightVisionToggle>
`
The log file is the BindingLoadingErrors.log ? 

I don't actually know which version worked for me before. I downloaded it the day I bought my stream deck so I assume it might be version : version 2.2.1 I'll try to reinstall this version later on tonight. I'll keep you posted. 

Thanks for responding this quickly 👍

**Comment by mhwlng** [comment]
I need the full bindings file and the full log file from the plugin directory

**Comment by mhwlng** [comment]
Do you really need two keyboard bindings for 1 function?
Can you remove one? I think the plugin presses both keys, which means that  the NV turns on and off again?

**Comment by RoyLachman** [comment]
I think I found the issue .

In game I've set the key bind to this key -> : 
When i was trouble shooting I set the bind to -> N 

But in-game the game registers the : key different to what it's called on my keyboard it seems (might be wrong keyboard driver). Somehow the streamdeck wasn't able to find the key I was pressing. I've set it to N and deleted the second entry and it's working like a charm again :)
