### ISSUE TITLE
Elite Dangerous Buttons Failure

### ISSUE THREAD

**Issue by mattgordon320** [mhwlng/streamdeck-elite#25]
Hi mhwlng,

Big fan of the application. While everything in game seems to be working fine (with the exception of me getting profiles to export read only) I've noticed that the program is occasionally crashing silently in the background or having problems. Any advice you might be able to give me in hunting down what's going on would be very much appreciated. Let me know if there is any other information I can provide and I'd be happy to. One of several logs follows:

`Source
Elite Dangerous Buttons

Summary
Stopped working

Date
‎10/‎20/‎2020 11:31 PM

Status
Report sent

Description
Faulting Application Path:	C:\Users\Illus\AppData\Roaming\Elgato\StreamDeck\Plugins\com.mhwlng.elite.sdPlugin\com.mhwlng.elite.exe

Problem signature
Problem Event Name:	CLR20r3
Problem Signature 01:	com.mhwlng.elite.exe
Problem Signature 02:	2.2.4.0
Problem Signature 03:	d11ff0b3
Problem Signature 04:	System.Drawing
Problem Signature 05:	4.8.3752.0
Problem Signature 06:	5c7a23f7
Problem Signature 07:	341
Problem Signature 08:	0
Problem Signature 09:	System.InvalidOperationException
OS Version:	10.0.18363.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	2beb
Additional Information 2:	2beba6fb4680d73a8c78ca7c24ccdb46
Additional Information 3:	a7ac
Additional Information 4:	a7ac965a9f5121c1f7a54c1e163698dc

Extra information about the problem
Bucket ID:	ef937441b3312deebcbe73d5ebe22f09 (2071220241259704073)
`

Matt

**Comment by mhwlng** [comment]
I would need to know the exact steps, to reliably reproduce the problem, to be able to fix it.

Unfortunately, the provided information is not enough to pinpoint the problem.

Note, that there is a log file in the plugin directory, that may contain more useful information.

**Comment by mhwlng** [comment]
please try v2.2.6, which adds more logging to the log file in the plugin directory

**Comment by mattgordon320** [comment]
Hey mgwlng, sorry for the long absence. Got laid off and had to take care of the normal life stuff. Computer crashed and having to reinstall from scratch. Will start with the new version and see where things go from there.
