### ISSUE TITLE
Disabling FSS Scanner switches Hud Mode to combat

### ISSUE THREAD

**Issue by Behelith-Vanyar** [mhwlng/streamdeck-elite#26]
Pressing the FSS Scanner button once enables the FSS Scanner and sets the Hud Mode to Analysis
Pressing the FSS Scanner button once more disables the FSS Scanner and sets the Hud Mode to Combat

If I press the hotkeys on keyboard this doesn't happen

Since I'm using the FSS scanner while exploring, when I come out of FSS Mode I need the Hud Mode to stay in "Analysis" to scan the next system.

Not sure if the automatic Hod Mode switching is done on purpose.

**Comment by mhwlng** [comment]
yes it's done on purpose. 
I'll think about adding a configuration option to the button in a next version.

**Comment by mhwlng** [comment]
new option was added to FSS button in 2.2.7
