### ISSUE TITLE
Feture Request: Elgato Multi Action Compatibility 

### ISSUE THREAD

**Issue by TenroNamikaze** [mhwlng/streamdeck-elite#27]
Would it be possible to add compatibility for Elgato's Multi Action Button?
I have already confirmed with Elgato that custom plugins are able to be used with the button, however they need to be programmed to be compatible. 
The though behind this is to allow the player to get combat ready from one button press after interdiction i.e. Activate combat mode -> deploy hardpoints -> target enemy -> issue fighter commands ect.
Really appreciate your hard work on the plugin.

**Comment by mhwlng** [comment]
see version 2.2.8
