### ISSUE TITLE
Elite Dangerous Buttons has stopped working

### ISSUE THREAD

**Issue by luilegeant** [mhwlng/streamdeck-elite#31]
Hello,

First of all thank you for the amazing job.

**Problem**
The plugin crashes when editing the elite keybindings.
![CrashOnControlsEdit](https://user-images.githubusercontent.com/8501519/101985310-88e6a300-3c87-11eb-9ce8-ee516a131f0e.PNG)

**Expected behaviour**
The application does not crash. 😄 

**How to reproduce** (at least for me)
- I have a current set of programmed "actions" from this plugin configured on my stream deck.
- My streamdeck is showing these "actions" currently (I use it as a list of things I should not forget to set).
- I've changed my hotas in this case, but it did happen previously if I changed my hotas to another usb port. (see next line if you don't understand why I mention this)
- I start elite and need to reconfigure some/all keybindings (you know how elite is famous to remember those) 😢 
- I open the Elite > Options > Controls to set and reset my keybindings...
- I change the presets from what elite selected for me (in this case _"Keyboard And Mouse"_) and I select Empty
- About 2 seconds later crash... (See picture above)
- Here is the log file.
[pluginlog.log](https://github.com/mhwlng/streamdeck-elite/files/5683152/pluginlog.log)
- I press 
- I set up some controls
- I click cancel or apply and get an exception again => although this one is not very regular.

Complementary information:
- it is a Steam install of Elite Dangerous and it is started via Steam (no idea if it has an impact)

**Comment by mhwlng** [comment]
The error message in the log is :

The process cannot access the file 'C:\Users\luilegeant\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\StartPreset.start' because it is being used by another process.

So, something is locking that file, causing the plugin to fail.

**Comment by mhwlng** [comment]
I added a retry mechanism in version 2.3.1 for reading StartPreset.start

please try if that fixes your problem

**Comment by luilegeant** [comment]
Amazing, it seems to have done the trick !
I did the same process as described above and switch to various pre-sets and no crash 🥳 

The log file seems to correlate that everything went fine.
[pluginlog.log](https://github.com/mhwlng/streamdeck-elite/files/5684371/pluginlog.log)

Thank you, for me this can close the ticket.
