### ISSUE TITLE
Question: What does the static button "Codex" refer to?

### ISSUE THREAD

**Issue by CMDRmiko0001** [mhwlng/streamdeck-elite#32]
Hi,
i stumbled upon this static button while setting up my stream deck for Elite: Dangerous.
I´m assuming this links to the Codex-page in the right cockpit panel, but i can´t get it to work.
I can´t find a corresponding setting in the E:D options>control settings to assign a keybinding to.

Edit: As i digged further, another question arose: Why are there double Static buttons (e.g. Nightvision ON|OFF) when there are Toggle buttons with the same functionality?

Any help in this regard is much appreciated.
Thx for making this awesome tool.

**Comment by mhwlng** [comment]
1)

The codex button links to the binding : OpenCodexGoToDiscovery 

on my system, it's not bound to any button, so won't do anything : 

	<OpenCodexGoToDiscovery>
		<Primary Device="{NoDevice}" Key="" />
		<Secondary Device="{NoDevice}" Key="" />
	</OpenCodexGoToDiscovery>

you can see the binding if you open the static.html file in the plugin directory.

2)

The double static buttons on/off are only meant for multi actions.

e.g. if you add 'nightvision on' as one action in a multi-action button and the nightvision is already on before you press the button, then it won't toggle it off again, when you press the multi-action button.
