### ISSUE TITLE
Streamdeck Software Forgets/Can't see Plugin After Changes to Manifest

### ISSUE THREAD

**Issue by TheHandyman1641** [mhwlng/streamdeck-elite#34]
mhwlng       

        Just like the title says. The Streamdeck software doesn't recognize the plugin after I make the necessary changes to the manifest to allow for automated profile changes.
 
        My first step was to create my button layouts and all profiles I needed. There were 4 all together including "Elite Dangerous Main XL". I exported all profiles into "C:\Users\AppData\Roaming\Elgato\StreamDeck\Plugins\com.mhwlng.elite.sdPlugin".

        Second,  I made my changes to the manifest. You should be able to see this bellow...
 ....
 ....
  "SDKVersion": 2,
  "Software": {
    "MinimumVersion": "4.6.1"
  },
  "Profiles": [
    {
	"Name":"Elite Dangerous Main XL",
	"ReadOnly":true,
	"DeviceType":2,
	"DontAutoSwitchWhenInstalled":false
    },
    {
	"Name:Elite Dangerous landing Gear XL",
	"ReadOnly":true,
	"DeviceType":2,
	"DontAutoSwitchWhenInstalled"true
    },
    {
	"Name:"Elite Dangerous Hardpoints XL",
	"ReadOnly":true,
	"DeviceType":2,
	"DontAutoSwitchWhenInstalled"true
    },
    {
	"Name:"Elite Dangerous Cargo Scoop XL",
	"ReadOnly":true,
	"DeviceType":2,
	"DontAutoSwitchWhenInstalled"true
    }
  ]  
}

        Third step I deleted the profiles in the Streamdeck software and closed the program via the windows taskbar menu in the bottom right and launched the program again. This is where the problem arose. When I opened the Streamdeck software I was not automaticly prompted to "Install profiles from plugin" so I selected "More Actions" in the bottom right of the window, scrolled throughout the list of plugins, and the Elite Dangerous Plugin wasn't in the list.

        I have tried deleting the appdata Elite Dangerous plugin folder, reinstalling the plugin and pasting from a backup the 4 exported profiles and manifest. However, this results in the same issue of the plugin "not being found" by the Streamdeck software.

        I doubt this is a problem with the plugin itself or even the stream deck software. I'm more keen to believe this is a problem with my pore instruction following skills LOL and having no knowledge of coding. I realize this my be silly mistake on my end but I'm so excited to use this great tool you have created and I would greatly appreciate any help you might be able to provide. 

Zach

**Comment by mhwlng** [comment]
you forgot a quote :

"Name:"Elite Dangerous Cargo Scoop XL",
