### ISSUE TITLE
[Idea] Animated GIF-Support

### ISSUE THREAD

**Issue by DarkNachtara** [mhwlng/streamdeck-elite#35]
I would like to have flashy Bottons if a System needs some 
attention like Overhead-Warning. 
That would be nice

**Comment by mhwlng** [comment]
Unfortunately, this is technically not possible.
Animated gifs are not supported bij the streamdeck api for the setimage SDK function.
This was confirmed on reddit by the streamdeck developers, a year ago.

https://www.reddit.com/r/StreamDeckSDK/comments/e0g0y6/when_i_use_setimage_with_an_animated_gif_i_only/
