### ISSUE TITLE
On all except the alarm button the image paths are incorrect after browsing/selecting an image

### ISSUE THREAD

**Issue by Behelith-Vanyar** [mhwlng/streamdeck-elite#39]
Streamdeck software version: 5.0.1.14252
Streamdeck-elite version: 2.3.7

After selecting a png image on the HDD the path to the image is wrongly applied (in the file path box).
For example the path to an image:
D:\AppData\StreamDeck\Elite\Galaxy Map - ON.png
Is shown as:
C:\fakepath\D%3A%2FAppData%2FStreamDeck%2FElite%2FGalaxy%20Map%20-%20ON.png

The issue occurs with any of the buttons except the alarm button

Relevant files in attachment:
[Streamdeck-Elite.zip](https://github.com/mhwlng/streamdeck-elite/files/7099825/Streamdeck-Elite.zip)

**Comment by mhwlng** [comment]
Please check the plugin log file for errors. 
You see this fakepath if the plugin is not running/crashed.
Also try starting streamdeck.exe as administrator.
Also try to put the image in the plugin directory.

**Comment by mhwlng** [comment]
I looked at the log

I think it has something to do with this error :

2021-09-02 16:24:12.6445|FATAL|com.mhwlng.elite|1|Directory doesn't exist C:\Users\RND\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings
2021-09-02 16:24:13.4249|FATAL|com.mhwlng.elite|1|Elite Api: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.String.Join(String separator, String[] value)
   at Elite.Program.GetKeyBindings(Object threadContext)
   at Elite.Program.Main(String[] args)

So, it can't find the elite dangerous keyboard binding directory :

I don't know where the bindings are on your system?
And why they are not in the standard location?
(or there may be an access rights issue ?)

**Comment by Behelith-Vanyar** [comment]
The issue is solved.
I didn't restore the Custom.3.0.binds and other settings files after reinstalling my PC and the game.
Thanks for the extremely quick reply and sorry for taking your time.
