### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by mbadsey** [mhwlng/streamdeck-elite#4]
Hey, Its really great to see some integration with Elite Dangerous, Have been meaning to get back into the game! however, none of the buttons are working with elite dangerous, Everything changes as it should but when anything is pressed on the Elgato Stream Deck nothing actually happens.

I have tried changing the button preset config from, "keyboard" , "Keyboard & Mouse" etc, i dont have my Sim controls plugged in yet but , any idea? would be great!

**Comment by mhwlng** [comment]
I assume that you are using the latest plugin (the one with the alarm buttons)

there is a logs directory and also a pluginlog.log file in  

%userprofile%\AppData\Roaming\Elgato\StreamDeck\Plugins\com.mhwlng.elite.sdPlugin

Are there any errors in these log files ?

what is the content of the StartPreset.start file in :

%userprofile%\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\

and is there a corresponding .....3.0.binds file in the same directory ?

**Comment by mbadsey** [comment]
yeh latest release,
[pluginlog.log](https://github.com/mhwlng/streamdeck-elite/files/4172002/pluginlog.log)

in the directory [%userprofile%\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\]

only 1 file, StartPreset.Start contents "KeyboardMouseOnly"

**Comment by mbadsey** [comment]
Also, Does this account for Steam Installation? as the directory with the requested file is here
Z:\SteamLibrary\steamapps\common\Elite Dangerous\Products\elite-dangerous-64\ControlSchemes

Just a thought!

**Comment by mhwlng** [comment]
as you can see in the log file :
file not found C:\Users\mbads\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\KeyboardMouseOnly.3.0.binds

I use a custom control scheme, which puts the file in the bindings directory.

I will change the plugin to also look into the controlschemes directory.

**Comment by mhwlng** [comment]
v 1.4.0 is out

Previous versions only worked with custom key binding files.
Now, when a default key binding file is selected, then also the steam library is searched for the binds file.
