### ISSUE TITLE
Buttons not working with Elite Dangerous

### ISSUE THREAD

**Issue by Fatpav72** [mhwlng/streamdeck-elite#40]
Hi,
I've just purchased a Stream Deck and installed all the files that you've kindly created. I've set my Stream Deck up and started Elite.
None of the buttons work in the game however when I use the alternative switches (from my HOTAS etc) the buttons indicate what the should do if I had pressed them.
 I'm really sorry to bother you with this but I was wondering what I am missing?

Thanks

**Comment by mhwlng** [comment]
You need keyboard bindings in elite. 
If there is only a joystick or mouse binding then it won't work. 
There is also a log file in the plugin directory that may contain error messages.
 You can also try to restart streamdeck.exe

**Comment by Fatpav72** [comment]
Many thanks for getting back to me so quickly.
I do have keyboard bindings along with the custom bindings for my HOTAS. I read through the details of the program and made sure that I had a keyboard binding for every action that I was requesting the Stream deck to perform. I also have restarted and reinstalled Stream deck to see if that helped.
 Do the keyboard bindings have to be the primary settings and the HOTAS the secondary? My Joystick is the Saitek x55 btw.
As I mentioned earlier, the buttons on the stream deck indicate they are doing the actions requested when I select the according action with a switch on my joystick (Landing Gear showing on and off, supercruise 'crossing out' when docked etc.) but they don't actual control the game from the Stream deck EXCEPT for the four buttons that I assigned to the COMMS, NAV, SYSTEM & ROLE panels, they switch when operated from the Stream deck.
 I'm running ED in borderless mode.
 Any help to get this sorted would be most welcome as the program looks great, the keys and actions on the Stream deck look awesome and it would really enhance the experience.

Many thanks

**Comment by mhwlng** [comment]
Please check the log file in the plugin directory for errors

please post the file here

**Comment by Fatpav72** [comment]
[pluginlog.log](https://github.com/mhwlng/streamdeck-elite/files/7190092/pluginlog.log)

Is this the file you need?

**Comment by mhwlng** [comment]
thanks, I don't see any errors in that file

You can also try to run streamdeck.exe as administrator.  
For some people that was needed (not for everybody)

If that doesn't fix the problem, then please post the files from this directory here :

C:\Users\darre\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings

also please export your streamdeck profile, and post it here.

**Comment by Fatpav72** [comment]
Hi,
Many thanks for all your help. I've got everything working now. I think there was an error in my bindings file. I removed all the garbage in there and everything 'fell into place'.
 The Profile for the stream deck is awesome! many thanks for sorting that.

Kindest regards
