### ISSUE TITLE
FSS Button not working

### ISSUE THREAD

**Issue by suraklin-save** [mhwlng/streamdeck-elite#41]
Hello,

i am trying to use the FSS button, but it doesn't work. I think it's because i am using a german qwertz keyboard and it is bound to the "umlaut" "ä".
Plugin log error:
2021-12-23 22:55:25.1952|FATAL|com.mhwlng.elite|6|ExtractKeyStrokes Exception: System.ArgumentException: Der angeforderte Wert "DIKÄ" konnte nicht gefunden werden.
   bei System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   bei System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   bei System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   bei Elite.CommandTools.ExtractKeyStrokes(String macroText)

Sorry about the german text.

Binding is:
	<ExplorationFSSEnter>
		<Primary Device="Keyboard" Key="Key_ä" />
		<Secondary Device="231D0125" Key="Joy_20" />
	</ExplorationFSSEnter>

Is there a way to get it to work?
Also there are two other umlaute, ö and ü.

Thank you very much for your help in advance :D

**Comment by suraklin-save** [comment]
An additional information.
The above plugin error Message was displayed in the german windows text editor.
If i open it i notepad+ it displays something else. I will uplode the files
[Custom.4.0.txt](https://github.com/mhwlng/streamdeck-elite/files/7771642/Custom.4.0.txt)
[pluginlog.log](https://github.com/mhwlng/streamdeck-elite/files/7771643/pluginlog.log)
.

**Comment by mhwlng** [comment]
see this comment in the readme :

**When using Odyssey, the on-foot binding must be 'custom'. (this will happen automatically once you make at least one on-foot keyboard binding) If you see a default binding name, then the plugin won't work correctly.**

you have these key bindings : Custom,Custom,KeyboardMouseOnly,KeyboardMouseOnly

that is the the reason why it doesn't work for you.

if all key bindings are set to custom, then it's ok
