### ISSUE TITLE
Plugin crash when using "$", "*", "ù" or "^" characters on french keyboard (W11)

### ISSUE THREAD

**Issue by PierreMalasiewicz** [mhwlng/streamdeck-elite#42]
Hi,

I have a problem since a few updates, the keys mapped with any of these four characters won't work : "$", "*", "ù" or "^"
I'm using a french keyboard layout on W11 with ED Odyssey.
I sent the plugin log with the exception attached

[pluginlog.log](https://github.com/mhwlng/streamdeck-elite/files/8748087/pluginlog.log)

**Comment by mhwlng** [comment]
I see that you used these binds files. 
Custom,Custom,Custom,SaitekX52
That won't work. It has to be all custom bindings.

I think that should also fix the mapping problem....

if it doesn't, then please also post your keyboard custom.4.0.binds file
