### ISSUE TITLE
Some buttons not recognised in control settings

### ISSUE THREAD

**Issue by DarrenMKL** [mhwlng/streamdeck-elite#43]
Hi there, firstly thank you do doing this.

I am setting up my Stream Deck to use and using your plugin, I have many options on my deck working, landing gear, cargo scoop, panel switching, power pips, hardpoint deployment, but I have some that don't I can't set them in the control options it's as if ED doesn't recognise the button/key. They are Supercruise, Hypercruise, Use Shield Cell, Chaff launcher, Open Galaxy Map, Open System Map and Enter FSS mode. I am using the 'keyboard only no mouse' selected for flight controls. Which become custom when I add my T Flight Hotas flight controls to the settings. All other options I have on my stream deck I can confirm by pressing them and they confirm the selection.

Is this a case of deleting the button and doing it again until it is (a Frontier feature) or am I missing something else.

Thanks
Darren
Version 2.4.3

Ps. Frontier store launcher edition Elite Dangerous Odyssey.

**Comment by mhwlng** [comment]
please post your binding file and plugin log file here

**Comment by mhwlng** [comment]
p.s. Are you sure that you added keybindings yourself for all bindings that didn't have them ?

for example, I checked my file :

"C:\Program Files (x86)\Steam\steamapps\common\Elite Dangerous\Products\elite-dangerous-odyssey-64\ControlSchemes\ClassicKeyboardOnly.binds"

and there is no key defined for galaxy map, supercruise, hyperspace etc. etc
```
<GalaxyMapOpen>
		<Primary Device="{NoDevice}" Key="" />
		<Secondary Device="{NoDevice}" Key="" />
<Supercruise>
		<Primary Device="{NoDevice}" Key="" />
		<Secondary Device="{NoDevice}" Key="" />
	</Supercruise>
	<Hyperspace>
		<Primary Device="{NoDevice}" Key="" />
		<Secondary Device="{NoDevice}" Key="" />
	</Hyperspace>
	</GalaxyMapOpen>
```

then the plugin won't work

**Comment by DarrenMKL** [comment]
Both attached.

It seems to be trying to find ClassicKeyboardOnly binds file. Should I rename my Custom.4.0.binds to that?

"there is no key defined for galaxy map, supercruise, hyperspace" so do I just have to add an assigned key in the binds file for it to work, if that's all it is then my problem will be fixed.

If so that's my "little thing I missed" moment :) It's just I couldn't add the key assignment in game, the way I always did it. But then how is it connected to the button option?


[Custom.4.0.zip](https://github.com/mhwlng/streamdeck-elite/files/10098922/Custom.4.0.zip)
[pluginlog.log](https://github.com/mhwlng/streamdeck-elite/files/10098923/pluginlog.log)

**Comment by mhwlng** [comment]
```
startpreset contents : KeyboardMouseOnly
KeyboardMouseOnly
Custom
Custom
```

all 4 bindings must say custom.

don't rename any files

you must edit at least one key, then it will change to custom.
once you start adding the missing key bindings then it will work.

**Comment by DarrenMKL** [comment]
Ok I have done that, all 4 are custom.

All fixed though, I was coming at it from the wrong direction thinking the Stream Deck buttons for Elite options were assigned keys, but they are ED operation connected not key connected which makes total sense. They need just any key assigned to them in game.

My apologies for not getting that.
Thanks
Darren

**Comment by mhwlng** [comment]
Ok  great :-)
