### ISSUE TITLE
process causing wakelock

### ISSUE THREAD

**Issue by jixxed** [mhwlng/streamdeck-elite#44]
The Elite Dangerous Buttons (32 bit) process keeps the system awake.
There is some audio playback in the app that opens an audio stream but never closes it.
![image](https://user-images.githubusercontent.com/14129491/204998864-619e31f6-4583-4f2d-b557-1dc40ec2f40b.png)

This does not happen if you start the system and NOT press any buttons. Once you press a button that has audio attached, you get an indefinite wakelock. Terminating the process is the only way to fix it. After terminating the process:
![image](https://user-images.githubusercontent.com/14129491/204999518-dc5acdaa-245b-4354-ab96-8c06a38250b3.png)

The app should not keep an audio stream open after it has played a sound.

**Comment by mhwlng** [comment]
can you simply not use audio for the buttons ?

**Comment by jixxed** [comment]
I have no sounds setup for the buttons

**Comment by mhwlng** [comment]
ok, I will investigate when I have time...

**Comment by mhwlng** [comment]
version 2.4.4

don't initialize AudioPlaybackEngine if no sounds are defined.

**Comment by jixxed** [comment]
issue is fixed for me. out of curiosity, does this still happen if you do define sounds?

**Comment by mhwlng** [comment]
Yes. for performance reasons AudioPlaybackEngine is initialized once  at the first sound and never disposed while stream deck exe is running.
