### ISSUE TITLE
Not every flag implemented as a possible profile

### ISSUE THREAD

**Issue by electrofloat** [mhwlng/streamdeck-elite#45]
Hi!

I noticed that here: https://github.com/mhwlng/streamdeck-elite/wiki/Automatic-Profile-Switching
not every profile mentioned that is possible in the status.json as flags. (https://elite-journal.readthedocs.io/en/latest/Status%20File/)

Especially I'd like to have a profile for supercruise and in wing because for the smaller stream deck there's just not enough space to put every option on it, so I'd divide them up to different profiles/modes the game is in.

**Comment by mhwlng** [comment]
see 2.4.8

**Comment by electrofloat** [comment]
That was fast. Thank you!
