### ISSUE TITLE
Automatic profile switching does not happen anymore

### ISSUE THREAD

**Issue by electrofloat** [mhwlng/streamdeck-elite#46]
Hi!

At first everything worked great. Even the new Supercruise, InWing profiles. After that I started to create other - non ED - profiles and  set one as a default one, installed/uninstalled other plugins, etc. Ever since the automatic profile switching does not happen anymore.

I even associated the ED Main profile with Elite Dangerous: Odyssey application but it does not even switch to that when I'm starting the game.

Is there any restriction on how these profiles should work? Should I not install any other plugins/profiles?

[pluginlog.log](https://pastebin.com/EecKjE99)

**Comment by electrofloat** [comment]
Or maybe the issue is that when I tried it out, my phone was not associated with the app yet, so I was only checking the streamdeck app on itself on windows while playing the game to see if it switches or not.
After that I associated, I think that is where it stopped working. Probably because the device ID does not match? I set the DeviceType to 0 (classic) is there one for mobile too?

**Comment by mhwlng** [comment]
you have profiles for StreamDeckClassic
Profile Found : Elite Dangerous Main for StreamDeckClassic

the only device it finds is StreamDeckMobile 
[Id: 7C4FF402844F457669F98B17E1A42507 Type: StreamDeckMobile Size: Rows: 3 Columns: 5]

StreamDeckMobile  is not supported. 
see wiki for supported devices
only classic, mini, xl, plus
