### ISSUE TITLE
Support for StreamDeckMobile

### ISSUE THREAD

**Issue by electrofloat** [mhwlng/streamdeck-elite#47]
The software currently only supports:
```
            FindProfiles(DeviceType.StreamDeckClassic, manifest);
            FindProfiles(DeviceType.StreamDeckMini, manifest);
            FindProfiles(DeviceType.StreamDeckXL, manifest);

            FindProfiles(DeviceType.StreamDeckPlus, manifest);
```
Please add support for StreamDeckMobile too.

**Comment by mhwlng** [comment]
see 2.5.0

I don't have this software and have no idea if it actually supports profile switching,

**Comment by electrofloat** [comment]
Thanks!

This is just a frontend for ios/android, which you can use for 30 days for free and for developers if they need more time they can extend the free period.
On my mobile it looks exactly like the SteamDeck Classic with just the 3x5 buttons.

and the automatic profile switch works great now, thanks.
