### ISSUE TITLE
FSS/DSS Actions

### ISSUE THREAD

**Issue by DerTomDerTwitch** [mhwlng/streamdeck-elite#48]
Maybe I'm missing something, but if not: It would be great to be able to allow buttons for actions regarding the FSS/DSS modes:

FSS
* Discovery Scan (press+hold)
* Target current signal
* Zoom In/Out
* And for the new dials on the steamdeck maybe the tunings

DSS
* Next Filter
* Previous Filter
* Toggle Front / Back View

**Comment by mhwlng** [comment]
I am not familiar with any of these mechanisms. 

please provide a list of the key bindings in your .binding file, that are linked to each of your required functions.

**Comment by DerTomDerTwitch** [comment]
Lightning fast reply. Awesome!
Alright, they are as follows (ignore my weird bindings, I fly HOTAS and use the most weird key bindings just for the StreamDeck)

FSS -> DiscoveryScan (button has to be kept pressed for roughly 3 seconds)
```
        <ExplorationFSSDiscoveryScan>
		<Primary Device="vJoy" DeviceIndex="0" Key="Joy_10" />
		<Secondary Device="Keyboard" Key="Key_D">
			<Modifier Device="Keyboard" Key="Key_LeftControl" />
			<Modifier Device="Keyboard" Key="Key_LeftShift" />
			<Modifier Device="Keyboard" Key="Key_LeftAlt" />
		</Secondary>
	</ExplorationFSSDiscoveryScan>
```
FSS -> Target current signal
```
	<ExplorationFSSTarget>
		<Primary Device="334440CC" Key="Joy_3" />
		<Secondary Device="Keyboard" Key="Key_T">
			<Modifier Device="Keyboard" Key="Key_LeftAlt" />
			<Modifier Device="Keyboard" Key="Key_LeftControl" />
			<Modifier Device="Keyboard" Key="Key_LeftShift" />
		</Secondary>
	</ExplorationFSSTarget>
```
FSS -> Zoom In / ZoomOut
```
	<ExplorationFSSZoomIn>
		<Primary Device="Mouse" Key="Mouse_1" />
		<Secondary Device="{NoDevice}" Key="" />
	</ExplorationFSSZoomIn>
	<ExplorationFSSZoomOut>
		<Primary Device="Mouse" Key="Mouse_2" />
		<Secondary Device="{NoDevice}" Key="" />
	</ExplorationFSSZoomOut>
```
SAA -> Next Filter / Prev Filter
```
	<ExplorationSAANextGenus>
		<Primary Device="33448194" Key="Joy_26" />
		<Secondary Device="{NoDevice}" Key="" />
	</ExplorationSAANextGenus>
	<ExplorationSAAPreviousGenus>
		<Primary Device="33448194" Key="Joy_24" />
		<Secondary Device="{NoDevice}" Key="" />
	</ExplorationSAAPreviousGenus>
```
SAA -> Toggle Front/Back (can be switched between "Toggle" and "Hold")
```
	<ExplorationSAAChangeScannedAreaViewToggle>
		<Primary Device="334440CC" Key="Joy_3" />
		<Secondary Device="{NoDevice}" Key="" />
		<ToggleOn Value="1" />
	</ExplorationSAAChangeScannedAreaViewToggle>
```
I'm not sure about the bindings for the tunings (these are axes not buttons). Have to dig a bit deeper to find those

**Comment by mhwlng** [comment]
I assume that only 
ExplorationFSSDiscoveryScan, ExplorationFSSZoomIn,ExplorationFSSZoomOut kan be kept pressed 
so they would be Repeating Static Button AND dials .

ExplorationSAAChangeScannedAreaViewToggle, ExplorationSAANextGenus, ExplorationSAAPreviousGenus, ExplorationFSSTarget would be single keypresses and would be only static buttons

**Comment by mhwlng** [comment]
please replace attached files in the plugin directory (and add key bindings in elite)
[Elite.zip](https://github.com/mhwlng/streamdeck-elite/files/10229643/Elite.zip)

%appdata%\Elgato\StreamDeck\Plugins\com.mhwlng.elite.sdPlugin\PropertyInspector\Elite

let me know if that works ok

If there is a problem you can edit those 3 files yourself  with any binding until it's ok and send me the files
