### ISSUE TITLE
Add Static Button for Shutdown Field Neutralizer

### ISSUE THREAD

**Issue by CarlEdman** [mhwlng/streamdeck-elite#50]
This is triggerable by a bindable keyboard shortcut/joystick button and is listed as "TriggerFieldNeutraliser" in the .binds file.

**Comment by mhwlng** [comment]
support already exists

just add this line to Static.html under option group Combat :
```
<option value="TriggerFieldNeutraliser">Field Neutraliser</option>
```
![image](https://user-images.githubusercontent.com/1388886/222636410-63a6ec6a-13a3-44e7-8e2c-a15202370ecf.png)

I'll add this line in a next version

**Comment by CarlEdman** [comment]
Thanks!
