### ISSUE TITLE
Power Button does not reliably work as expected wenn pressing long

### ISSUE THREAD

**Issue by arminbl** [mhwlng/streamdeck-elite#51]
If pressing a power button long it is intended to set the power distributor to 4 pips. This does not always work as expected when not starting from reset position.

How to reproduce:
1. Reset power distributor
2. Press a power button long to get 4 pips
3. Press another power button long to get 4 pips
4. In this state one power button has zero pips. Pressing this power button long will set the power distributor only to 3 Pips

There are other ways to reproduce, but this is the easiest to describe.

**Comment by mhwlng** [comment]
I'll investigate when I have some time...

**Comment by mhwlng** [comment]
fixed in v2.5.7
