### ISSUE TITLE
Some buttons aren't working

### ISSUE THREAD

**Issue by Fliegevieh** [mhwlng/streamdeck-elite#52]
Hey there,
I have the problem that some buttons like:

Shield Cell Bank & Flight Assist (Both Static and Toggle button) aren't working. I press them and just nothing happens. I tried:

> Running Stream Deck as Administrator

> Restarting Elite Dangerous (Odyssey)

> Serching in Logs for errors

> Restarting my PC

> Reinstalling the Plugin

I only found the errors:

`file not found C:\Users\xxx\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\KeyboardMouseOnly.4.0.binds

file also not found C:\Users\xxx\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\KeyboardMouseOnly.3.0.binds

file also not found C:\Users\xxx\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\KeyboardMouseOnly.binds
2023-03-06 20:10:33.0697|ERROR|com.mhwlng.elite

steam file not found D:\SteamLibrary\steamapps\common\Elite Dangerous\Products\elite-dangerous-64\ControlSchemes\KeyboardMouseOnly.4.0.binds

steam file also not found D:\SteamLibrary\steamapps\common\Elite Dangerous\Products\elite-dangerous-64\ControlSchemes\KeyboardMouseOnly.3.0.binds`

The other buttons are justing working fine.

Maybe I understood something wrong or I configured the plugin wrong. Could you please help me?

Kind regards
Paul
![EliteDeck](https://user-images.githubusercontent.com/125214053/223220693-e647a2ce-0ac0-4a81-b0fe-34759f5c0757.png)

**Comment by mhwlng** [comment]
you are using the standard binding KeyboardMouseOnly
you need to use custom binds. 
all buttons need a keyboard binding.
