### ISSUE TITLE
Odyssey - custom binding

### ISSUE THREAD

**Issue by fatlazycat** [mhwlng/streamdeck-elite#54]
Hi, does the on foot binding need to explicitly be called 'custom' or just any non default one will work ?

I have several bindings files that i have made, I guess could duplicate to custom if needed.

Thanks for the amazing plugin !

**Comment by mhwlng** [comment]
No it has to be custom. All 4 bindings in odyssey need to be in the same , single, binds file called custom

**Comment by fatlazycat** [comment]
I've had some issues recently. But appears to be working with Custom only set for on foot and a bespoke name for the others i.e. 2 binds files.
