### ISSUE TITLE
A few interface suggestions

### ISSUE THREAD

**Issue by CarlEdman** [mhwlng/streamdeck-elite#55]
Maybe these should be separate issues, but I didn't want to hammer the issues list with so many tiny additions.

1. Can we have the number of additional hops listed in addition/instead of/optionally on the "Target Next Hop" button?  I find that the only reason I keep the hyperspace icon (for which I have a throttle control) is to see the hop count remaining.
2. The "Target Next Hop" button should show as "disabled" when there are no more hops.
3. Could we have the "Field Neutralizer" button show as alarmed when the thargoids have launched a shutdown field?  That would nicely match the behavior of some other status/countermeasure buttons.
4. The FSS button should show as "disabled" even when in hyperdrive when the velocity is above the minimum as FSS cannot be activated then.

**Comment by mhwlng** [comment]
1,2 i don't know what the target next hop button is. if it is a static button, then it's not possible to add game information to it.

3,4 is not possible. the game does not provide this information

**Comment by CarlEdman** [comment]
1,2 Sorry.  It is called "Next Jump Dest" and it is a static button.  I understand you cannot do anything custom for regular static buttons, but I thought that maybe it could be made a special button just like the "Hyperspace" button, except its function would be to target the next jump destination.
3,4 I thought this info might be in the same stream that the plugin gets the information on heat (for highlighting the Heatsink button), hardpoints, landing gear, cargo scoop, etc.  But if it is not accessible to the plugin, this of course cannot be done.

**Comment by mhwlng** [comment]
1,2 I'll consider it for a future version.

**Comment by mhwlng** [comment]
see new route button in version 2.5.8
