### ISSUE TITLE
Pips and tiles don't work after latest streamdeck update

### ISSUE THREAD

**Issue by error55o** [mhwlng/streamdeck-elite#56]
I have updated to the latest version of Stream Deck and not the pips don't show and the tiles no longer change from black to gray

**Comment by error55o** [comment]
update, the buttons do function but not graphically as they used to

**Comment by mhwlng** [comment]
I don't know what you mean?

**Comment by mhwlng** [comment]
If you add an image like this then it doesn't work

![image](https://user-images.githubusercontent.com/1388886/225193900-07e633bc-c462-4cc9-bf88-6455396e8d71.png)

**Comment by mhwlng** [comment]
streamdeck 6.1.0.18521
tested on XL, classic and + streamdecks, **all with latest streamdeck firmware**
plugin 2.5.7

![image](https://user-images.githubusercontent.com/1388886/225212716-7c9cc77e-cbdb-4286-83a2-208a955047ef.png)

**Comment by error55o** [comment]
I kinda fixed it by restoring defaults but now the ENG/SYS/WEP buttons move like they are using WASD not the arrow keys I have them bound to, more experimenting is being conducted tonight

**Comment by mhwlng** [comment]
All bindings must be set to custom

**Comment by error55o** [comment]
they were but not being picked up, fixed by rebinding the keys differently then reverting to original bindings, I am closing this issue, it seems that it was just a tempary issue
