### ISSUE TITLE
Automatic Profile Switching Installation

### ISSUE THREAD

**Issue by BobaBrett** [mhwlng/streamdeck-elite#57]
Hi,

I have just spent a while following the wiki instructions for the profile switching, restarting the stream deck over and over to get it to try and import the exported (and configured) profiles. 

The step that was missing, was actually launching elite dangerous, at which point the prompt to install the profiles popped up and all teh profiles got installed

May be worth updating the documentation with this knowledge for others in the future! Not sure if its a newer version of the stream deck software, or because I am on a ClassicV2 perhaps that makes it behave differently!

**Comment by mhwlng** [comment]
It’s the wiki:
>>sometimes triggering an automatic profile switch, will display the installation popup.


Wording could be improved….
