### ISSUE TITLE
FSS button is without function

### ISSUE THREAD

**Issue by diwobo** [mhwlng/streamdeck-elite#59]
The FSS buttons have no function for me. The images change, but the FSS is not called up. The plugin was uninstalled and reinstalled, but this did not help. Previously the plugin worked perfectly. Unfortunately, it is not clear why it has stopped working. All other functions except the FSS can be operated. FSS can be called up using the keyboard shortcut. Is there anything known here that can affect the function?

**Comment by mhwlng** [comment]
please provide your key binding file and plugin log file

**Comment by diwobo** [comment]
[Elite_Dangerous_Profil.zip](https://github.com/mhwlng/streamdeck-elite/files/13531284/Elite_Dangerous_Profil.zip)
[StreamDeck5.log](https://github.com/mhwlng/streamdeck-elite/files/13531321/StreamDeck5.log)

I don't know if that is the right logfile.

**Comment by mhwlng** [comment]
Hello,Unfortunately neither of these files are the correct file that I need.

the key .binding file is a file from elite dangerous 

probably here :

%LocalAppData%\Frontier Developments\Elite Dangerous\Options\Bindings\


and the plugin log file is in the directory that the plugin is installed in.

probably here:

%appdata%\Elgato\StreamDeck\Plugins\com.mhwlng.elite.sdPlugin

**Comment by diwobo** [comment]
I am sorry to have caused this inconvenience. We were able to solve the problem in the meantime, there was an error in the USB drivers which caused chaos in the whole system. Apparently something got mixed up during an update. The ticket can be closed.
