### ISSUE TITLE
images are not part of release package

### ISSUE THREAD

**Issue by luilegeant** [mhwlng/streamdeck-elite#6]
Hello, 
First of all, thank you for this great work !

I managed to get the previous version (1.7.0) running on my stream deck xl. But no images were available, so I've downloaded the source code, copied the images from the image folder and pasted it next to the icons in `%appdata%\Elgato\StreamDeck\Plugins\com.mhwlng.elite.sdPlugin\Images`. Doing this made it work like a charm.

To install the current release (1.8.0), here is the process I went through:
- stopped the elgato app
- removed the old extension folder
- started the elgato app
- installed (double click) on the installation package

Result:
- all keys in the stream deck now show a question mark
- there is no images in the release 1.8.0 package either
- the actions still works (eg: I can toggle my lights as before)

Expected result:
- the image are in the release package
- I don't get question mark for each action of this plugin (due to missing images).

Again, thank you for the great work

**Comment by mhwlng** [comment]
Hello,
There are not supposed to be images in the package. 
You are supposed to provide your own button images.
The images that are included in the source code are only meant as simple examples, used for testing the plugin.
If you wish to use these example images, then you will need to copy them somewhere yourself.
They don't have to be stored in the plugin images directory, 
So, then, when you update the plugin, they are not lost.
