### ISSUE TITLE
Version 2.6.0 shows internally as 2.5.9

### ISSUE THREAD

**Issue by lwt-pressy** [mhwlng/streamdeck-elite#60]
Hi, when installing I got a warning, that it is already installed. So I uninstalled it and installed the new version. After Installing the new version it still shows up as 2.5.9. I double checked, that I used the new version.

**Comment by mhwlng** [comment]
You're right. I replaced the .streamDeckPlugin file release

**Comment by lwt-pressy** [comment]
thx, worked
