### ISSUE TITLE
Elite dangerous binding changes

### ISSUE THREAD

**Issue by Rainmangames** [mhwlng/streamdeck-elite#63]
with the 132 button update, looks like elite is changing their bindings from 4.0 to 4.1 and the app couldnt find em because of it.had to do a fresh install today and was scratching my head
 got mine all sorted but figured id give ya shout! i love this thing thank you so much for all the hard work!

**Comment by mhwlng** [comment]
Thanks for letting me know!

This is now fixed in v2.7
