### ISSUE TITLE
Field Neutralizer has to be a Repeating Static Button [With Solution]

### ISSUE THREAD

**Issue by Cetheus** [mhwlng/streamdeck-elite#66]
Upon testing the Plugin, a Friend and I discovered, that the Field Neutralizer does not work with a normal "Static Button".
It has to be held down.

The solution is quite simple.
Open the File `%APPDATA%\Elgato\StreamDeck\Plugins\com.mhwlng.elite.sdPlugin\PropertyInspector\Elite\RepeatingStatic.html`
with any Text-Editor of your choice.

Now go to Line 21 `<optgroup label="Galaxy map">` and add the following lines before:
```
            <optgroup label="Combat">
                <option value="TriggerFieldNeutraliser">Field Neutraliser</option>
            </optgroup>
```

It should look like this:
```
        <select class="sdpi-item-value select sdProperty" id="function" oninput="setSettings()">
            <optgroup label="Combat">
                <option value="TriggerFieldNeutraliser">Field Neutraliser</option>
            </optgroup>
            <optgroup label="Galaxy map">
```

Now just restart the Stream Deck Software and you should be able to add the "Field Neturalizer" as a "Repeating Static Button"

**Comment by mhwlng** [comment]
Thanks
release 2.7.1 has this change.
