### ISSUE TITLE
Route issues

### ISSUE THREAD

**Issue by Sortam** [mhwlng/streamdeck-elite#67]
Hi mhwlng, 
I'm observing a couple of issues related to routes functionality:

1. When a route is created using the map, the number of jumps is shown on the **Hyperjump** and **Route** buttons as expected, but when you clear the route, the number of jumps stays on both buttons until another route is selected or you jump to another system.

2. The disabled state of the Route button is almost nonexistent. It may be in this state after the game starts (not always), but I've never seen it after the route is finished, so the expected "_disabled : Remaining Jumps In Route = 0_" doesn't work most of the time.

And I just found out that the numbers on both buttons are cleared and the route button is disabled when you select any system in the system map (using the "**Set Targe**t" icon) without plotting the route.

It seems that the _NavRouteClear_ event is not handled properly in these cases (just a guess). I downloaded the source and tried to solve it myself, but I'm not a professional developer and it turned out that I don't have enough knowledge to do this - I did several experiments but it didn't help.  So I hope you can find some time to take a look at these issues.
 
Thank you for this project!

**Comment by mhwlng** [comment]
please try new 2.7.2 version

**Comment by Sortam** [comment]
Route clearing works well now, but the remaining jumps counter does not decrease along the route in this version. If a route has 6 jumps, the buttons will show "6" until the very last jump.

**Comment by mhwlng** [comment]
Ok, I have deleted the 2.7.2 release and went back to the old system and only included new NavRouteClear handling.

please try 2.7.3

(I haven't played this game in over 5 years. so I can't easily check myself without reinstalling it and figuring out how to play it again...)

**Comment by Sortam** [comment]
> please try 2.7.3

Works fine now. Counters count, clearing clears. Thank you so much!

> (I haven't played this game in over 5 years. so I can't easily check myself without reinstalling it and figuring out how to play it again...)

I see, no problem at all. I'm okay to be a tester :) 
I have not played for three years, now I have returned to the game and found this amazing plugin. I'm glad you're still supporting it even though you don't play the game. I really appreciate it.
Thanks again!
