### ISSUE TITLE
Can't get the plugin to work

### ISSUE THREAD

**Issue by grotteaux** [mhwlng/streamdeck-elite#68]
Thanks for all of your hard work on this! I am hoping you can help me? The plugin is not working and I keep getting this error in the log:

2024-08-20 10:25:30.9333|FATAL|com.mhwlng.elite|12|ExtractKeyStrokes Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at Elite.CommandTools.ExtractKeyStrokes(String macroText)

Thank you!

**Comment by mhwlng** [comment]
Please zip the files in the game bindings directory and post here
Is there a particular function that causes this error?

**Comment by grotteaux** [comment]
Thanks for taking the time to help me! Here're the files you asked for. 
[Custom.4.0.binds.3346825729.zip](https://github.com/user-attachments/files/16681976/Custom.4.0.binds.3346825729.zip)

**Comment by mhwlng** [comment]
your StartPreset.4.start contains :
SaitekX56
Custom
KeyboardMouseOnly
KeyboardMouseOnly

that doesn't work (see instructions on github) they must all be 'custom'

All bindings must be 'custom'. (this will happen automatically once you make at least one on-foot keyboard binding) If you see a default binding name, then the plugin won't work correctly.

![image](https://github.com/user-attachments/assets/cd63ceed-c2aa-4759-9502-cd39855bf053)
