### ISSUE TITLE
Feature Request: Outstanding Bounty

### ISSUE THREAD

**Issue by Octo23** [mhwlng/streamdeck-elite#7]
Good Day, love the tool

Would it be possible to add a button that would report the current bounty on the selected ship?

If this is possible, things that I would like to see incorporated into the display.
Green or Orange text to indicate if the ship is an ally or not.
An indication if the KWS has been used against the ship.
Current bounty, which can change after a shipped has been scanned with the KWS.
Finally as a bonus, if the ship is Clean, has a Warrant or Wanted

**Comment by mhwlng** [comment]
Hi 
That's outside the scope of this plugin
the button is not big enough for all this information 
and there is no logical action when pressing the streamdeck button.
also the ShipTargeted doesn't contain all the information that you want (like if KWS has been used)

a display for the ShipTargeted event is in the https://github.com/mhwlng/fip-elite project :

![image](https://user-images.githubusercontent.com/1388886/81638381-4f139c80-9419-11ea-9c3d-8c69b2a46fde.png)

p.s. I just configure the KWS button to the same button as the laser. 
So KWS is always used when firing on a ship.
