### ISSUE TITLE
New to plugins and cant get this one to work. 

### ISSUE THREAD

**Issue by NinJesus3382** [mhwlng/streamdeck-elite#70]
I have installed this plugin to my stream deck plus and followed all the instructions, but i cant seem to get it to work. I have read through a good bit of the issues others have had and made sure i changed some control settings in each category but nothing seems to work. When I check the log there is no error given either. I'm sure its just me being dumb but i cant figure out what im doing worng. 

I have tried setting a button for each pip, super cruise, hardpoints, and landing gear with no luck.

**Comment by mhwlng** [comment]
I'm sorry I have no idea. I don't see any clues in your message. This software only works with keyboard bindings. Not mouse or joystick bindings. The 4 keyboard binding categories should all say 'custom'

Try running streamdeck.exe as administrator

**Comment by NinJesus3382** [comment]
I did this. I have tried everything me and my tech friends can think of and everything you have told others to try. Thank you anyways.
