### ISSUE TITLE
Feature request: "Buttons" for watching inventory

### ISSUE THREAD

**Issue by lassevk** [mhwlng/streamdeck-elite#8]
When out gathering materials for engineering, it would be nice if I could configure one or more buttons on the unit to show an icon I choose + the number of units I have of a specified material.

For instance, I could configure a button to watch my inventory of Sulphur, or Conductive Components, so that while out gathering I have the numbers available at a glance.

They could function pretty much the same way as the display portion of the collector/prospector limpet buttons do, sans the actual key binding.

**Comment by mhwlng** [comment]
Sorry, that is out of the scope for this plugin.
There is also no logical function to link to that button press.

I am currently planning to add more engineering/material gathering related functionality and also plan to add integration with EDEngineer shopping list for this project :
https://github.com/mhwlng/fip-elite
https://forums.frontier.co.uk/threads/information-display-for-logitech-flight-instrument-panel.535231/

**Comment by mhwlng** [comment]
Just f.y.i

Integration with EDengineer now works in the FIP-elite project 
https://github.com/mhwlng/fip-elite :

![](https://i.imgur.com/cND15WL.png)

![](https://i.imgur.com/fGCBdzH.png)
